smlua_text_utils_course_acts_replace(COURSE_BOB, (" 1 GARDEN OF THE MORNING LIGHT"),	("WALLKICK ROAD OF THE STARTING GROUNDS"),	("TUNNEL OF THE BURNING FIRE"),	("HIDDEN ROOM OF HORRORS"),	("LEGENDS' OPTIONAL FIRSTIES"),	("REACH FOR THE SUMMIT"),	("GARDENING REDS"))

smlua_text_utils_course_acts_replace(COURSE_WF, (" 2 THE DAWN OF TIME"),	("THE DAWN OF COWARDICE"),	("THE DAWN OF SPEED"),	("THE DAWN OF TRICKY MANEUVERS"),	("THE DAWN OF SLIPPERY HELL"),	("THE DAWN OF HIDDEN MEANINGS"),	("THE DAWN OF COLLECTION"))

smlua_text_utils_course_acts_replace(COURSE_JRB, (" 3 FIGMENT OF DELIGHT"),	("DESTROYER OF AN APPARENT PEACE"),	("INSIDE THE HOT TOWER"),	("THE LONELY OUTER TOWER"),	("RED COIN HUNTING IN THE PEACEFUL VALLEY"),	("SHELL RIDE TO THE DISTANT CASTLE"),	("BIRD'S EYE SECRETS"))

smlua_text_utils_course_acts_replace(COURSE_CCM, (" 4 GREEN STONE ROAD"),	("ROCKY FIGHT"),	("THE HEXAGON TRIAL"),	("TRICKY WALLKICK TOWER"),	("SKY HIGH CANNONSHOT"),	("COLLECT THE CRYSTAL SHARDS"),	("CROSSOVER RACE"))

smlua_text_utils_course_acts_replace(COURSE_BBH, (" 5 FORSAKEN FORTRESS"),	("SWITCH BOX PATH TO THE SECRET ROOM"),	("LAVABOUNCE TO THE TOP"),	("THE VICIOUS FLAMING CORRIDOR"),	("PILLARS OF BURNING DEBRIS"),	("HIDDEN AT THE BORDER OF LIFE"),	("BLOODY TEARS OF A BROKEN SOUL"))

smlua_text_utils_course_acts_replace(COURSE_HMC, (" 6 SUMMER PLAYGROUND"),	("A BATTLE FOR THE LIGHT"),	("PIERCE THROUGH THE DEADLY SUN"),	("THE STAIRCASE WALLKICKS"),	("SKY HIGH YELLOW CASTLE?"),	("AN ARCH FULL OF FAKES"),	("SUNSHINE RED COINS"))

smlua_text_utils_course_acts_replace(COURSE_LLL, (" 7 TWILIGHT LANDSCAPE"),	("THE GLASS ASCENSION"),	("VANISH RUN TO THE HELLISH ROOM"),	("SECRETS OF THE MYTH HIMSELF"),	("THE BELOVED FUN SLIDE"),	("TRIAL OF THE SHALLOW DARKNESS"),	("RED COINS OF CRYSTALLINE MATTER"))

smlua_text_utils_course_acts_replace(COURSE_SSL, (" 8 SINKING DEFORESTATION"),	("INSIDE THE TREE TRUNK"),	("RIDING THROUGH THE DEADLY SWAMP"),	("THE BIG BUG ON THE TALL TREE"),	("ALONG THE CLIFFSIDE"),	("CAVERN OF FIRE AND FLAMES"),	("RED COINS OF A DYING LAND"))

smlua_text_utils_course_acts_replace(COURSE_DDD, (" 9 CASTLE OF BLIZZARDS"),	("VANISH INTO THE TALLEST TOWER"),	("THE OTHER TOWER'S HIDDEN LEDGE"),	("THROUGH THE DROWNED TUNNEL"),	("BLOOD RED FINANCES"),	("TRIPLE CAP COMBINATION"),	("FINDING SOULS IN THE COLD BREEZE"))

smlua_text_utils_course_acts_replace(COURSE_SL, ("10 VALLEY OF ILLUSION"),	("ATOP THE GREAT CASTLE"),	("CASTLE INSIDE ACROBATICS"),	("SEVERAL SLIDEY SLOPES"),	("THE ILLUSIONARY CAP"),	("THE FABLED HEXAGON CHAIN"),	("MASTERING THE ORANGE VALLEY"))

smlua_text_utils_course_acts_replace(COURSE_WDW, ("11 ENDARKENED CLIFFS"),	("UNDER YOUR TOES"),	("FLOATING PIECES OF MATTER"),	("VOLCANO BUILDING?"),	("ENDARKENED COINS"),	("SECRET OF THE STRANDED ISLAND"),	("WILD FLIGHT"))

smlua_text_utils_course_acts_replace(COURSE_TTM, ("12 TALL, TALL MELANCHOLY"),	("HIDDEN UNDER THE PRISMS"),	("CONTRASTING PATH"),	("END OF THE HEXAGON ROAD"),	("VANISHING UPTOWN RACE"),	("SHOCKING CROSSOVER CHALLENGE"),	("FRIGHTFUL WALLKICK COINS"))

smlua_text_utils_course_acts_replace(COURSE_THI, ("13 BLOSSOMING FANTASY"),	("BEAUTIFUL EYES"),	("FIRSTIES OF A DISTANT LAND"),	("SIGNS OF TRUE LOVE"),	("THE PRESENT STACK"),	("LOVE COLORED COINS"),	("OUR DARKEST SECRETS"))

smlua_text_utils_course_acts_replace(COURSE_TTC, ("14 A BRIGHTER FUTURE"),	("BLUE PLATFORM'S FIRE EXTINGUISING"),	("THROUGH THE SMALL CORRIDOR"),	("TRAVERSING GREATER HEIGHTS"),	("DISCOLORED SKY TOWER"),	("THE GREEN CASTLE'S HIDDEN TREASURE"),	("DOMINANCE OF ANOTHER WORLD"))

smlua_text_utils_course_acts_replace(COURSE_RR, ("15 REVENGE GLIMPSE PARADOX"),	("UNBREAKABLE IRRESPONSIBILITY"),	("IN THE TRAGEDY'S HEART"),	("POWER OF THE SHOOTING STARS"),	("MORBID ARCH WALLKICKS' HELL"),	("THE DREADED LONELY FORT"),	("THE FINAL PARADOX"))

smlua_text_utils_secret_star_replace(15 + 1, ("   LOST SKY PALACE"))
smlua_text_utils_secret_star_replace(16 + 1, ("   SPACE FACTORY"))
smlua_text_utils_secret_star_replace(17 + 1, ("   CATHEDRAL OF DESTINY"))
smlua_text_utils_secret_star_replace(18 + 1, ("   WINDY CLOUD COURT"))
smlua_text_utils_secret_star_replace(19 + 1, ("   TOXIC WASTE DEPTHS"))
smlua_text_utils_secret_star_replace(20 + 1, ("   TOWERS OF AKADIA"))
smlua_text_utils_secret_star_replace(21 + 1, ("   EYE OF THE DUST STORM"))
smlua_text_utils_secret_star_replace(22 + 1, ("   FRAGILE VAULT"))
smlua_text_utils_secret_star_replace(23 + 1, ("   REALM OF A GREATER NIGHT"))
smlua_text_utils_secret_star_replace(24 + 1, ("   HELL OF HOPE"))
smlua_text_utils_castle_secret_stars_replace(("   SECRET STARS"))
smlua_text_utils_extra_text_replace(0,("ONE OF THE TRAGEDY STARS"))