smlua_text_utils_course_acts_replace(COURSE_BOB, (" 1 MYSTERY MANSION"), 	("THE MISLEADING BOOKSHELVE'S"), 	("KEEN EYES FOR A FAKE FLOOR"), 	("TEASING STAR FROM THE GATE"), 	("KITCHEN PIPELINE'S CLOG "), 	("SECRET ROOM NAVIGATION"), 	("PINK BOB-OMB'S GUIDANCE"))

smlua_text_utils_course_acts_replace(COURSE_WF, (" 2 STORMY OCEANIC TOWN"), 	("SIMPLE CLIMB ATOP THE ILLUSION"), 	("OCEANIC METAL RING STAR"), 	("GREEN SPACE"), 	(" POLE, WALLKICK AND A CHURCH\n\
CHALLENGE"), 	("RODEO OF CLIMBS ABOVE WATER"), 	("SPEED FOOT SURFING"))

smlua_text_utils_course_acts_replace(COURSE_JRB, (" 3 SAND FUSION CAVERN"), 	("KING WHOMP'S IMMUNITY?"), 	("PERILOUS PAINFUL CLIMB"), 	("INSANITY BEYOND THE MOUNTAIN"), 	("LEAP OF FATE OR STATEGIC BOUNCING?"), 	("INSIDE THE LAVA PILLAR"), 	("JUST GIVE UP ALREADY! FOR PROS ONLY... SERIOUSLY"))

smlua_text_utils_course_acts_replace(COURSE_CCM, (" 4 NEW KING BOO'S PRISON"), 	("WALKICKS WILL WALLKICKS"), 	("PATH OF THE MIMICS"), 	("BORDER PANIC! SIDE OF THE PRISON!"), 	("THE PINACLE OF PRISON PARKOUR"), 	("WAIT NO THAT'S THE PINACLE"), 	("PRESENT LEFT BY THE ESCAPED TOAD"))

smlua_text_utils_course_acts_replace(COURSE_BBH, (" 5 FLOWERY FLOWER FIELD"), 	("STEEL WHEELS STAR OF HOPE"), 	("A TALLER BUILDING"), 	("CAREFUL HOPS AMOUNGS TREES"), 	("TIMED BLOCK IN THE HIDDEN ZONE"), 	("PERFECT SWIMMING WITH A SHELL"), 	("ONLY ONE WAY TO GET IT"))

smlua_text_utils_course_acts_replace(COURSE_HMC, (" 6 CRAZY STIRRING COCKTAIL"), 	("PINK TOWER'S TRIAL 1 BIG B"), 	("PINK TOWER'S TRIAL 2"), 	("ALL-STAR PARKOUR"), 	("HIGH SPEED LAVAKICKS"), 	("ACE IT, DON'T AMP YOURSELF"), 	("UPWAY FOR GLORY OR CHEESE?"))

smlua_text_utils_course_acts_replace(COURSE_LLL, (" 7 PEACEFUL JINGLE JUNGLE"), 	("BIG BLOCK BLOCKADE "), 	("STAR IN THE HUTS"), 	("INVISIBILITY AMONGST FLOWERS"), 	("QUICK FOOTING ON SAND"), 	("A SHELL OF A TIME"), 	("A WAY IN THE MAIN HUT"))

smlua_text_utils_course_acts_replace(COURSE_SSL, (" 8 INVASION FORESTIAL "), 	("MOTHERSHIP'S ABDUCTION "), 	("A CLOSER PEAK OF THE INVADERS"), 	("CUTTING THROUGH, CLIMBING UP"), 	("HALL OF TRUST"), 	("A BREEZE ABOVE NOTHING"), 	("COULD THAT LIGHT MEAN SOMETHING?"))

smlua_text_utils_course_acts_replace(COURSE_DDD, (" 9 MIRAGE TREE'S"), 	("ROOT OF THE PROBLEM?"), 	("THE TRICK IS TO TAP LIGTHLY"), 	("A TIMED CLOUD RACE"), 	("WHERE IS THE BRANCH?"), 	("JUMPING BOX CHALLENGE"), 	("THE HOUSE ABOVE CHAOS"))

smlua_text_utils_course_acts_replace(COURSE_SL, ("10 STATION 616"), 	("ABOVE STREAM'S OF SPACE"), 	("ANTI-GRAV ROADS"), 	("A QUIZZ WITHOUT LIMIT"), 	("WEST STATION STATUS NOT FORBIDDEN "), 	("OH NOES! IT'S LIGHT CHUCKYA TIME!"), 	("JUMPING FOR GLORY"))

smlua_text_utils_course_acts_replace(COURSE_WDW, ("11 MISTIC MIST'S REVENGE"), 	("CAN YOU TRUST THE MIST?"), 	("WARP WALLS ABOVE THE MIST"), 	("OF SOLID AND NON SOLID"), 	("BEYOND THE MIST EXPLORATION"), 	("CHURCH CLIMBING"), 	("ALTERNATE ENTRANCE "))

smlua_text_utils_course_acts_replace(COURSE_TTM, ("12 POISONOUS HOLLOWS"), 	("WHOMPS AND JUMPS"), 	("THE CLOSED ALCOVE"), 	("A SHELL OF A PROBLEM"), 	("SNUFIT PARKOUR, TAKE 200"), 	("METAL IN THE RED ZONE"), 	("MYSTERIOUS SIDE PATH"))

smlua_text_utils_course_acts_replace(COURSE_THI, ("13 HEATWAVE CANYON"), 	("SCALE BEYOND THE HEAT!"), 	("INFILTRATE THE FACTORY!"), 	("A QUICK CLIMB OF HAZARDS"), 	("SECRETS OF THE PYRAMID TOMB"), 	("A HINT NEEDED TREES ALIGNED!"), 	("NARROW PATH OF THE OASIS"))

smlua_text_utils_course_acts_replace(COURSE_TTC, ("14 DREADFUL GLOOMY LAND"), 	("TEAMWORK WITH THE ENEMY"), 	("ABYSMAL SPOOKY CAVE"), 	("SIDE CLIFF OF THE DARK LAND"), 	("THE OTHER END"), 	("DANGEROUS SLIPPIN'S SLOPES"), 	("SLICED MOON TOP"))

smlua_text_utils_course_acts_replace(COURSE_RR, ("15 STARDUST CONSTELLATION"), 	("CELESTIAL PATH"), 	("SWINGING THROUGH SPACE"), 	("CAN YOU PERFECT FLIGHT?"), 	("SOME PATH ABOVE NOTHINGNESS"), 	("??? THAT'S NOT THE BLACKROOM STAR"), 	("THREE FLOORS ONE YOU"))

smlua_text_utils_secret_star_replace(16, ("   FEARSOME ELITE TOWER"))
smlua_text_utils_secret_star_replace(17, ("   SWAMP OF OLD DIVINITY"))
smlua_text_utils_secret_star_replace(18, ("   ANIMOSITY MANSIONS"))
smlua_text_utils_secret_star_replace(19, ("   SKY ASCENSION "))
smlua_text_utils_secret_star_replace(20, ("   PATH OF THE GODS TRIAL"))
smlua_text_utils_secret_star_replace(21, ("   CONSUMING VOID TRIAL"))
smlua_text_utils_secret_star_replace(22, ("   SACRED POWER TRIAL "))
smlua_text_utils_secret_star_replace(23, ("   ECLIPSE OF FUSION"))
smlua_text_utils_secret_star_replace(24, ("   UNKNOWN ORIGINS"))
smlua_text_utils_secret_star_replace(25, ("   ECLIPSE OF THE DEVOURER"))
smlua_text_utils_castle_secret_stars_replace(("   ??? SECRET STAR!"))
smlua_text_utils_extra_text_replace(0,("??? SECRET STAR!"))