movtexqc_register("bob_1_Movtex_0", LEVEL_BOB, 1, 0)
movtexqc_register("wf_1_Movtex_0", LEVEL_WF, 1, 0)
movtexqc_register("jrb_1_Movtex_0", LEVEL_JRB, 1, 0)
movtexqc_register("ccm_1_Movtex_0", LEVEL_CCM, 1, 0)
movtexqc_register("bbh_1_Movtex_0", LEVEL_BBH, 1, 0)
movtexqc_register("bbh_2_Movtex_0", LEVEL_BBH, 2, 0)
movtexqc_register("hmc_1_Movtex_0", LEVEL_HMC, 1, 0)
movtexqc_register("lll_1_Movtex_0", LEVEL_LLL, 1, 0)
movtexqc_register("lll_2_Movtex_0", LEVEL_LLL, 2, 0)
movtexqc_register("ssl_1_Movtex_0", LEVEL_SSL, 1, 0)
movtexqc_register("ssl_2_Movtex_0", LEVEL_SSL, 2, 0)
movtexqc_register("ddd_1_Movtex_0", LEVEL_DDD, 1, 0)
movtexqc_register("ddd_2_Movtex_0", LEVEL_DDD, 2, 0)
movtexqc_register("ddd_3_Movtex_0", LEVEL_DDD, 3, 0)
movtexqc_register("sl_1_Movtex_0", LEVEL_SL, 1, 0)
movtexqc_register("sl_2_Movtex_0", LEVEL_SL, 2, 0)
movtexqc_register("ttm_1_Movtex_0", LEVEL_TTM, 1, 0)
movtexqc_register("thi_1_Movtex_0", LEVEL_THI, 1, 0)
movtexqc_register("thi_2_Movtex_0", LEVEL_THI, 2, 0)
movtexqc_register("rr_1_Movtex_0", LEVEL_RR, 1, 0)

movtexqc_register("pss_1_Movtex_0", LEVEL_PSS, 1, 0)
movtexqc_register("sa_1_Movtex_0", LEVEL_SA, 1, 0)
movtexqc_register("sa_2_Movtex_0", LEVEL_SA, 2, 0)
movtexqc_register("wmotr_1_Movtex_0", LEVEL_WMOTR, 1, 0)

movtexqc_register("totwc_1_Movtex_0", LEVEL_TOTWC, 1, 0)
movtexqc_register("vcutm_1_Movtex_0", LEVEL_VCUTM, 1, 0)
movtexqc_register("cotmc_1_Movtex_0", LEVEL_COTMC, 1, 0)

movtexqc_register("bitdw_1_Movtex_0", LEVEL_BITDW, 1, 0)
movtexqc_register("bitfs_1_Movtex_0", LEVEL_BITFS, 1, 0)
movtexqc_register("bowser_1_Movtex_0", LEVEL_BOWSER_1, 1, 0)
movtexqc_register("bowser_2_Movtex_0", LEVEL_BOWSER_2, 1, 0)