smlua_text_utils_course_acts_replace(COURSE_BOB, (" 1 COCOCO LEVEL1"),	("COCOCO STAR"),	("FOOTRACE WITH KOOPA THE QUICK"),	("SHOOT TO THE ISLAND IN THE SKY"),	("FIND THE 8 RED COINS"),	("MARIO WINGS TO THE SKY"),	("BEHIND CHAIN CHOMP'S GATE"))

smlua_text_utils_course_acts_replace(COURSE_WF, (" 2 COCOCO LEVEL2"),	("COCOCO STAR"),	("TO THE TOP OF THE FORTRESS"),	("SHOOT INTO THE WILD BLUE"),	("RED COINS ON THE FLOATING ISLE"),	("FALL ONTO THE CAGED ISLAND"),	("BLAST AWAY THE WALL"))

smlua_text_utils_course_acts_replace(COURSE_JRB, (" 3 COCOCO LEVEL3"),	("COCOCO STAR"),	("CAN THE EEL COME OUT TO PLAY?"),	("TREASURE OF THE OCEAN CAVE"),	("RED COINS ON THE SHIP AFLOAT"),	("BLAST TO THE STONE PILLAR"),	("THROUGH THE JET STREAM"))
